name: dartcraft
version: 0.0.1
description: >-
  Dart WebGPU example project

environment:
  sdk: '>=2.17.0 <3.0.0'

publish_to: none

dependencies:
  image: ^4.0.0
  webgpu:
    git: https://github.com/brendan-duncan/dart_webgpu
