name: dartcraft
version: 0.0.1
description: >-
  Dart WebGPU example project

environment:
  sdk: '>=2.17.0 <3.0.0'

publish_to: none

dependencies:
  image: ^4.0.0
  webgpu:
    path: ../dart_webgpu

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
